"""Fan counts API router.

Serves the public read-only fan-count time series generated by snh48-fan-hub
scripts/social_monitor/fan_count_collector.py (social_record/fan_counts/).
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Query, Response

from website import config as cfg

router = APIRouter(prefix="/api/fans-stats", tags=["粉丝数记录页"])

TS_FORMAT = "%Y-%m-%d %H:%M:%S"


def _data_dir() -> Path:
    return Path(cfg.FAN_COUNTS_DATA_PATH)


def _load_latest() -> dict[str, Any]:
    path = _data_dir() / "latest.json"
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _load_series(days: int) -> dict[str, list[dict[str, Any]]]:
    path = _data_dir() / "fan_counts.jsonl"
    series: dict[str, list[dict[str, Any]]] = {}
    if not path.exists():
        return series
    cutoff = datetime.now() - timedelta(days=days)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return series
    for line in lines[-5000:]:
        line = line.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(record, dict):
            continue
        platform = str(record.get("platform") or "")
        followers = record.get("followers")
        ts = str(record.get("ts") or "")
        if not platform or followers is None or not ts:
            continue
        try:
            ts_dt = datetime.strptime(ts, TS_FORMAT)
        except ValueError:
            continue
        if ts_dt < cutoff:
            continue
        series.setdefault(platform, []).append({"ts": ts, "followers": int(followers)})
    return series


@router.get("")
def get_fans_stats(
    response: Response,
    days: int = Query(30, ge=1, le=180),
):
    """Return the latest per-platform fan counts and the recent time series."""
    response.headers["Cache-Control"] = "public, max-age=300"
    latest = _load_latest()
    platforms = latest.get("platforms") if isinstance(latest.get("platforms"), dict) else {}
    return {
        "available": bool(platforms),
        "fetched_at": str(latest.get("fetched_at", "")),
        "days": days,
        "platforms": platforms,
        "series": _load_series(days),
    }
