"""
Gift replies API router.

Reads the small derived dataset generated by snh48-fan-hub and exposes a
password-protected, paginated view for the admin page.
"""
from __future__ import annotations

import csv
import hmac
import json
import re
from math import ceil
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request, Response, status

from website import config as cfg
from website.rate_limiter import check_admin_login_limit, get_client_ip

router = APIRouter(prefix="/api/gift-replies", tags=["礼物回复页"])

VALID_STATUSES = {"all", "replied", "unreplied"}
VALID_REPLY_TYPES = {"all", "text", "audio"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


async def verify_gift_replies_password(
    request: Request,
    x_gift_replies_password: str = Header(None, alias="X-Gift-Replies-Password"),
):
    """Verify the gift replies page password."""
    if not cfg.GIFT_REPLIES_PASSWORD:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="礼物回复页未启用",
    )
    if not x_gift_replies_password:
        check_gift_replies_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="需要密码",
        )
    if not hmac.compare_digest(cfg.GIFT_REPLIES_PASSWORD, x_gift_replies_password):
        check_gift_replies_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="密码错误",
        )
    return True


def check_gift_replies_login_limit(request: Request) -> None:
    check_admin_login_limit(get_client_ip(request), "礼物回复页密码尝试过于频繁，请稍后再试")


@router.get("/data")
def get_gift_replies_data(
    response: Response,
    page: int = Query(1, ge=1),
    page_size: int = Query(100, ge=1, le=500),
    status_filter: str = Query("all", alias="status"),
    gift_name: str = Query(""),
    sender: str = Query(""),
    reply_type: str = Query("all"),
    date_from: str = Query(""),
    date_to: str = Query(""),
    _=Depends(verify_gift_replies_password),
):
    """Return filtered, paginated gift rows with summary metadata."""
    response.headers["Cache-Control"] = "no-store"

    status_filter = status_filter.strip().lower()
    reply_type = reply_type.strip().lower()
    if status_filter not in VALID_STATUSES:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的回复状态")
    if reply_type not in VALID_REPLY_TYPES:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的回复类型")
    _validate_date("date_from", date_from)
    _validate_date("date_to", date_to)
    if date_from and date_to and date_from > date_to:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="日期范围无效")

    summary_doc = _load_summary_doc()
    rows = _load_gift_rows()
    filtered = _filter_rows(
        rows,
        status_filter=status_filter,
        gift_name=gift_name.strip(),
        sender=sender.strip(),
        reply_type=reply_type,
        date_from=date_from.strip(),
        date_to=date_to.strip(),
    )

    total = len(filtered)
    total_pages = max(1, ceil(total / page_size))
    start = (page - 1) * page_size
    end = start + page_size

    return {
        "generated_at": summary_doc.get("generated_at", ""),
        "timezone": summary_doc.get("timezone", "Asia/Shanghai"),
        "refresh_interval_seconds": _to_int(summary_doc.get("refresh_interval_seconds"), 60),
        "default_page_size": _to_int(summary_doc.get("default_page_size"), 100),
        "summary": summary_doc.get("summary", {}),
        "gift_catalog": _normalise_catalog(summary_doc.get("gift_catalog", [])),
        "items": filtered[start:end],
        "page": page,
        "page_size": page_size,
        "total": total,
        "total_pages": total_pages,
    }


@router.get("/summary")
def get_gift_replies_summary(
    response: Response,
    _=Depends(verify_gift_replies_password),
):
    """Return summary metadata without the paginated gift list."""
    response.headers["Cache-Control"] = "no-store"
    summary_doc = _load_summary_doc()
    return {
        "generated_at": summary_doc.get("generated_at", ""),
        "timezone": summary_doc.get("timezone", "Asia/Shanghai"),
        "refresh_interval_seconds": _to_int(summary_doc.get("refresh_interval_seconds"), 60),
        "default_page_size": _to_int(summary_doc.get("default_page_size"), 100),
        "summary": summary_doc.get("summary", {}),
        "gift_catalog": _normalise_catalog(summary_doc.get("gift_catalog", [])),
    }


def _data_dir() -> Path:
    return Path(cfg.GIFT_REPLIES_DIR)


def _load_summary_doc() -> dict[str, Any]:
    path = _data_dir() / "summary.json"
    if not path.exists():
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="礼物回复汇总数据未生成")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="礼物回复汇总数据读取失败") from exc


def _load_gift_rows() -> list[dict[str, Any]]:
    path = _data_dir() / "gifts.csv"
    if not path.exists():
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="礼物列表数据未生成")
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            return [_normalise_gift_row(row) for row in csv.DictReader(f)]
    except OSError as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="礼物列表数据读取失败") from exc


def _normalise_gift_row(row: dict[str, str]) -> dict[str, Any]:
    reply_types = _split_semicolon(row.get("all_reply_types", ""))
    if not reply_types:
        reply_types = [value for value in (row.get("first_reply_type"), row.get("latest_reply_type")) if value]
    reply_contents = _split_semicolon(row.get("all_reply_contents", ""))

    return {
        "gift_message_id": row.get("gift_message_id", ""),
        "gift_server_id": row.get("gift_server_id", ""),
        "gift_bj_time": row.get("gift_bj_time", ""),
        "sender_id": row.get("sender_id", ""),
        "sender_name": row.get("sender_name", ""),
        "receiver_name": row.get("receiver_name", ""),
        "gift_id": row.get("gift_id", ""),
        "gift_name": row.get("gift_name", ""),
        "gift_count": _to_int(row.get("gift_count"), 0),
        "gift_score": row.get("gift_score", ""),
        "gift_icon_url": row.get("gift_icon_url", ""),
        "gift_media_path": row.get("gift_media_path", ""),
        "reply_status": row.get("reply_status", "unreplied"),
        "has_reply": row.get("has_reply", "") == "1",
        "reply_count": _to_int(row.get("reply_count"), 0),
        "first_reply_message_id": row.get("first_reply_message_id", ""),
        "first_reply_bj_time": row.get("first_reply_bj_time", ""),
        "first_reply_type": row.get("first_reply_type", ""),
        "first_reply_sender_name": row.get("first_reply_sender_name", ""),
        "first_reply_content": row.get("first_reply_content", ""),
        "first_reply_duration_seconds": _to_int(row.get("first_reply_duration_seconds"), 0),
        "latest_reply_message_id": row.get("latest_reply_message_id", ""),
        "latest_reply_bj_time": row.get("latest_reply_bj_time", ""),
        "latest_reply_type": row.get("latest_reply_type", ""),
        "latest_reply_content": row.get("latest_reply_content", ""),
        "all_reply_message_ids": _split_semicolon(row.get("all_reply_message_ids", "")),
        "all_reply_bj_times": _split_semicolon(row.get("all_reply_bj_times", "")),
        "all_reply_types": reply_types,
        "all_reply_contents": reply_contents,
    }


def _normalise_catalog(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    catalog: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        catalog.append({
            "gift_id": str(item.get("gift_id", "")),
            "gift_name": str(item.get("gift_name", "")),
            "gift_icon_url": str(item.get("gift_icon_url", "")),
            "total_messages": _to_int(item.get("total_messages"), 0),
            "total_count": _to_int(item.get("total_count"), 0),
            "replied_messages": _to_int(item.get("replied_messages"), 0),
            "unreplied_messages": _to_int(item.get("unreplied_messages"), 0),
            "reply_rate": str(item.get("reply_rate", "")),
            "first_gift_bj_time": str(item.get("first_gift_bj_time", "")),
            "latest_gift_bj_time": str(item.get("latest_gift_bj_time", "")),
        })
    return catalog


def _filter_rows(
    rows: list[dict[str, Any]],
    *,
    status_filter: str,
    gift_name: str,
    sender: str,
    reply_type: str,
    date_from: str,
    date_to: str,
) -> list[dict[str, Any]]:
    gift_name_lower = gift_name.lower()
    sender_lower = sender.lower()

    filtered: list[dict[str, Any]] = []
    for row in rows:
        if status_filter != "all" and row["reply_status"] != status_filter:
            continue
        if gift_name_lower and gift_name_lower not in row["gift_name"].lower():
            continue
        if sender_lower and sender_lower not in row["sender_name"].lower():
            continue
        if reply_type != "all" and not _row_matches_reply_type(row, reply_type):
            continue
        gift_date = row["gift_bj_time"][:10]
        if date_from and gift_date < date_from:
            continue
        if date_to and gift_date > date_to:
            continue
        filtered.append(row)
    return filtered


def _row_matches_reply_type(row: dict[str, Any], reply_type: str) -> bool:
    reply_types = set(row.get("all_reply_types") or [])
    if reply_type == "text":
        return "GIFTREPLY" in reply_types
    if reply_type == "audio":
        return "AUDIO_GIFT_REPLY" in reply_types
    return True


def _validate_date(label: str, value: str) -> None:
    if value and not DATE_RE.match(value.strip()):
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=f"{label} 日期格式应为 YYYY-MM-DD")


def _split_semicolon(value: str | None) -> list[str]:
    if not value:
        return []
    return [item for item in value.split(";") if item]


def _to_int(value: Any, default: int) -> int:
    if value in (None, ""):
        return default
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default
