"""
Score gifts API router.

Reads the small derived scoring gift dataset generated by snh48-fan-hub and
exposes password-protected statistics and detail rows for the admin dashboard.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import re
import threading
from io import BytesIO
from datetime import datetime, timedelta, timezone
from math import ceil
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape
from zipfile import ZIP_DEFLATED, ZipFile

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request, Response, status

from website import config as cfg
from website.rate_limiter import check_admin_login_limit, get_client_ip
from website.shared_runtime_state import SharedStateError, SharedStatePeerError, execute_mutation, register_mutator

router = APIRouter(prefix="/api/score-gifts", tags=["计分礼物页"])

VALID_SOURCES = {"all", "room", "live"}
VALID_SORTS = {"time_desc", "score_desc"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
UNKNOWN_SENDER_VALUES = {"", "?"}
BJ_TZ = timezone(timedelta(hours=8))
LIVE_BUSINESS_STATE_FILENAME = "live_business_fulfillments.json"
BUSINESS_STATUSES = {"redeemed", "unredeemed", "uncertain"}
SIGNATURE_FIELDS = (
    "id",
    "source",
    "event_time",
    "sender_name",
    "sender_id",
    "gift_id",
    "gift_name",
    "gift_count",
    "unit_score",
    "total_score",
    "live_id",
    "live_title",
    "live_bj_time",
    "danmu_offset",
    "danmu_file",
    "danmu_line_number",
    "raw_content",
)

_cache_lock = threading.Lock()
_cache_mtime_ns = -1
_cache_doc: dict[str, Any] = {}


async def verify_score_gifts_password(
    request: Request,
    x_score_gifts_password: str = Header(None, alias="X-Score-Gifts-Password"),
):
    """Verify the score gifts page password."""
    expected = cfg.SCORE_GIFTS_PASSWORD
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="计分礼物页未启用",
        )
    if not x_score_gifts_password:
        check_score_gifts_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="需要密码",
        )
    if not hmac.compare_digest(expected, x_score_gifts_password):
        check_score_gifts_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="密码错误",
        )
    return True


def check_score_gifts_login_limit(request: Request) -> None:
    check_admin_login_limit(get_client_ip(request), "计分礼物页密码尝试过于频繁，请稍后再试")


@router.get("/data")
def get_score_gifts_data(
    response: Response,
    page: int = Query(1, ge=1),
    page_size: int = Query(100, ge=1, le=500),
    source: str = Query("all"),
    gift_name: str = Query(""),
    sender: str = Query(""),
    date_from: str = Query(""),
    date_to: str = Query(""),
    sort: str = Query("time_desc"),
    _=Depends(verify_score_gifts_password),
):
    """Return filtered score gift statistics and paginated detail rows."""
    response.headers["Cache-Control"] = "no-store"

    doc, rows = _filtered_detail_rows(
        source=source,
        gift_name=gift_name,
        sender=sender,
        date_from=date_from,
        date_to=date_to,
        sort=sort,
    )

    total = len(rows)
    total_pages = max(1, ceil(total / page_size))
    start = (page - 1) * page_size
    end = start + page_size

    return {
        "generated_at": str(doc.get("generated_at", "")),
        "timezone": str(doc.get("timezone", "Asia/Shanghai")),
        "refresh_interval_seconds": _to_int(doc.get("refresh_interval_seconds"), 30),
        "default_page_size": _to_int(doc.get("default_page_size"), 100),
        "summary": doc.get("summary", {}),
        "filtered_summary": _summary(rows),
        "gift_catalog": _normalise_distribution(doc.get("gift_catalog") or doc.get("gift_distribution") or []),
        "gift_distribution": _gift_distribution(rows),
        "sender_distribution": _sender_distribution(rows),
        "daily_distribution": _daily_distribution(rows),
        "live_sessions": _live_sessions(rows),
        "items": rows[start:end],
        "page": page,
        "page_size": page_size,
        "total": total,
        "total_pages": total_pages,
    }


@router.get("/export.xlsx")
def export_score_gifts_xlsx(
    source: str = Query("all"),
    gift_name: str = Query(""),
    sender: str = Query(""),
    date_from: str = Query(""),
    date_to: str = Query(""),
    sort: str = Query("time_desc"),
    _=Depends(verify_score_gifts_password),
):
    """Export all filtered score gift detail rows as an XLSX workbook."""
    doc, rows = _filtered_detail_rows(
        source=source,
        gift_name=gift_name,
        sender=sender,
        date_from=date_from,
        date_to=date_to,
        sort=sort,
    )
    stamp = datetime.now(BJ_TZ).strftime("%Y%m%d_%H%M%S")
    filename = f"score_gifts_{stamp}.xlsx"
    return Response(
        content=_build_score_gifts_xlsx(rows, str(doc.get("generated_at", ""))),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={
            "Cache-Control": "no-store",
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )


@router.get("/summary")
def get_score_gifts_summary(
    response: Response,
    _=Depends(verify_score_gifts_password),
):
    """Return score gift summary metadata without detail rows."""
    response.headers["Cache-Control"] = "no-store"
    doc = _load_dataset()
    return {
        "generated_at": str(doc.get("generated_at", "")),
        "timezone": str(doc.get("timezone", "Asia/Shanghai")),
        "refresh_interval_seconds": _to_int(doc.get("refresh_interval_seconds"), 30),
        "default_page_size": _to_int(doc.get("default_page_size"), 100),
        "summary": doc.get("summary", {}),
        "gift_distribution": _normalise_distribution(doc.get("gift_distribution", [])),
        "sender_distribution": _normalise_distribution(doc.get("sender_distribution", [])),
        "daily_distribution": _normalise_distribution(doc.get("daily_distribution", [])),
        "live_sessions": _normalise_distribution(doc.get("live_sessions", [])),
    }


@router.post("/business-review")
async def update_score_gift_business_review(
    request: Request,
    _=Depends(verify_score_gifts_password),
):
    """Verify or manually override one live score-gift business result."""
    try:
        payload = await request.json()
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="JSON 格式无效") from exc
    if not isinstance(payload, dict):
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="请求体格式无效")

    action = _clean_text(payload.get("action"))
    item_id = _clean_text(payload.get("item_id"))
    if action not in {"verify", "override"}:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效操作")
    if not item_id:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="缺少记录 ID")

    try:
        response = execute_mutation("score_business", "business_review", payload)
    except SharedStatePeerError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.detail) from exc
    except SharedStateError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"业务核实状态跨服务器保存失败：{exc}",
        ) from exc
    result = response.get("result") if isinstance(response.get("result"), dict) else {}
    return {
        "ok": True,
        "item_id": str(result.get("item_id") or item_id),
        "record": result.get("record") or {},
        "fields": result.get("fields") or {},
    }


def _business_review_mutator(
    state: dict[str, Any], payload: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any]]:
    action = _clean_text(payload.get("action"))
    item_id = _clean_text(payload.get("item_id"))
    if action not in {"verify", "override"}:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效操作")
    if not item_id:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="缺少记录 ID")

    doc = _load_dataset()
    item = next((row for row in _normalise_items(doc.get("items", [])) if row["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="记录不存在")
    if item["source"] != "live":
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="只有直播计分礼物支持业务核实")

    records = state.setdefault("records", {})
    if not isinstance(records, dict):
        records = {}
        state["records"] = records

    signature = _live_business_item_signature(item)
    existing = records.get(item_id)
    if not isinstance(existing, dict) or _clean_text(existing.get("input_signature")) != signature:
        existing = {}

    if action == "verify":
        current_status = _normalise_business_status(existing.get("status") or item.get("business_status"))
        if current_status not in BUSINESS_STATUSES:
            raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="当前记录还没有可核实的业务分析结果")
        record = dict(existing)
        record.update(_record_from_item(item))
        record["status"] = current_status
        record["review_status"] = "verified"
        record["reviewed_at"] = _bj_now()
        record["reviewed_by"] = "website"
        record.setdefault("analysis_source", item.get("business_analysis_source") or "codex")
    else:
        current_status = _normalise_business_status(payload.get("business_status"))
        if current_status not in BUSINESS_STATUSES:
            raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="请选择有效的兑换状态")
        record = {
            "item_id": item_id,
            "input_signature": signature,
            "status": current_status,
            "business_type": _clean_text(payload.get("business_type")),
            "business_content": _clean_text(payload.get("business_content")),
            "business_offset": _clean_text(payload.get("business_offset")),
            "business_line_number": _clean_text(payload.get("business_line_number")),
            "evidence": _clean_text(payload.get("evidence")),
            "reasoning": _clean_text(payload.get("reasoning") or "网站人工修正"),
            "confidence": "high",
            "review_status": "verified",
            "analysis_source": "manual",
            "analysis_model": "",
            "analysis_prompt_version": _to_int(payload.get("analysis_prompt_version"), 1),
            "analyzed_at": _bj_now(),
            "reviewed_at": _bj_now(),
            "reviewed_by": "website",
            "business_window_seconds": 0,
        }

    record["item_id"] = item_id
    record["input_signature"] = signature
    records[item_id] = record
    result = {
        "item_id": item_id,
        "record": record,
        "fields": _business_fields_from_record(record),
    }
    return state, result


register_mutator("score_business", "business_review", _business_review_mutator)


def _data_path() -> Path:
    return Path(cfg.SCORE_GIFTS_DATA_PATH)


def _business_state_path() -> Path:
    return _data_path().parent / LIVE_BUSINESS_STATE_FILENAME


def _filtered_detail_rows(
    *,
    source: str,
    gift_name: str,
    sender: str,
    date_from: str,
    date_to: str,
    sort: str,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    source = source.strip().lower()
    sort = sort.strip().lower()
    if source not in VALID_SOURCES:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的数据来源")
    if sort not in VALID_SORTS:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的排序方式")
    _validate_date("date_from", date_from)
    _validate_date("date_to", date_to)
    if date_from and date_to and date_from > date_to:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="日期范围无效")

    doc = _load_dataset()
    items = _normalise_items(doc.get("items", []))
    _apply_business_state_overrides(items)
    rows = _filter_rows(
        items,
        source=source,
        gift_name=gift_name.strip(),
        sender=sender.strip(),
        date_from=date_from.strip(),
        date_to=date_to.strip(),
    )
    return doc, _sort_rows(rows, sort)


def _load_dataset() -> dict[str, Any]:
    global _cache_mtime_ns, _cache_doc

    path = _data_path()
    if not path.exists():
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据未生成")

    stat = path.stat()
    if _cache_mtime_ns == stat.st_mtime_ns:
        return _cache_doc

    with _cache_lock:
        stat = path.stat()
        if _cache_mtime_ns == stat.st_mtime_ns:
            return _cache_doc
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据读取失败") from exc
        if not isinstance(doc, dict):
            raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据格式无效")
        _cache_mtime_ns = stat.st_mtime_ns
        _cache_doc = doc
        return _cache_doc


def _normalise_items(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    rows: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        rows.append({
            "id": str(item.get("id", "")),
            "source": str(item.get("source", "")),
            "source_label": str(item.get("source_label", "")),
            "event_time": str(item.get("event_time", "")),
            "date": str(item.get("date", "")),
            "sender_name": str(item.get("sender_name", "")),
            "sender_id": str(item.get("sender_id", "")),
            "sender_id_source": str(item.get("sender_id_source", "")),
            "sender_id_match_status": str(item.get("sender_id_match_status", "")),
            "receiver_name": str(item.get("receiver_name", "")),
            "gift_id": str(item.get("gift_id", "")),
            "gift_name": str(item.get("gift_name", "")),
            "gift_count": _to_int(item.get("gift_count"), 0),
            "unit_score": _to_float(item.get("unit_score"), 0.0),
            "total_score": _to_float(item.get("total_score"), 0.0),
            "score_source": str(item.get("score_source", "")),
            "gift_icon_url": str(item.get("gift_icon_url", "")),
            "gift_media_path": str(item.get("gift_media_path", "")),
            "message_id": str(item.get("message_id", "")),
            "server_id": str(item.get("server_id", "")),
            "source_jsonl_lineno": str(item.get("source_jsonl_lineno", "")),
            "live_id": str(item.get("live_id", "")),
            "live_title": str(item.get("live_title", "")),
            "live_bj_time": str(item.get("live_bj_time", "")),
            "danmu_offset": str(item.get("danmu_offset", "")),
            "danmu_offset_seconds": _to_float(item.get("danmu_offset_seconds"), 0.0),
            "danmu_file": str(item.get("danmu_file", "")),
            "danmu_line_number": str(item.get("danmu_line_number", "")),
            "raw_content": str(item.get("raw_content", "")),
            "fulfillment_status": str(item.get("fulfillment_status", "")),
            "fulfillment_label": str(item.get("fulfillment_label", "")),
            "fulfillment_detail": str(item.get("fulfillment_detail", "")),
            "fulfillment_time": str(item.get("fulfillment_time", "")),
            "fulfillment_source": str(item.get("fulfillment_source", "")),
            "room_has_reply": bool(item.get("room_has_reply", False)),
            "room_reply_status": str(item.get("room_reply_status", "")),
            "room_reply_count": _to_int(item.get("room_reply_count"), 0),
            "room_first_reply_message_id": str(item.get("room_first_reply_message_id", "")),
            "room_first_reply_time": str(item.get("room_first_reply_time", "")),
            "room_first_reply_type": str(item.get("room_first_reply_type", "")),
            "room_first_reply_content": str(item.get("room_first_reply_content", "")),
            "room_latest_reply_message_id": str(item.get("room_latest_reply_message_id", "")),
            "room_latest_reply_time": str(item.get("room_latest_reply_time", "")),
            "room_latest_reply_type": str(item.get("room_latest_reply_type", "")),
            "room_latest_reply_content": str(item.get("room_latest_reply_content", "")),
            "business_status": str(item.get("business_status", "")),
            "business_type": str(item.get("business_type", "")),
            "business_content": str(item.get("business_content", "")),
            "business_offset": str(item.get("business_offset", "")),
            "business_line_number": str(item.get("business_line_number", "")),
            "business_window_seconds": _to_int(item.get("business_window_seconds"), 0),
            "business_review_status": str(item.get("business_review_status", "")),
            "business_reviewed_at": str(item.get("business_reviewed_at", "")),
            "business_reviewed_by": str(item.get("business_reviewed_by", "")),
            "business_analysis_source": str(item.get("business_analysis_source", "")),
            "business_analysis_model": str(item.get("business_analysis_model", "")),
            "business_analysis_prompt_version": _to_int(item.get("business_analysis_prompt_version"), 0),
            "business_analysis_at": str(item.get("business_analysis_at", "")),
            "business_analysis_confidence": str(item.get("business_analysis_confidence", "")),
            "business_analysis_reasoning": str(item.get("business_analysis_reasoning", "")),
            "business_evidence": str(item.get("business_evidence", "")),
            "business_input_signature": str(item.get("business_input_signature", "")),
        })
    return rows


def _filter_rows(
    rows: list[dict[str, Any]],
    *,
    source: str,
    gift_name: str,
    sender: str,
    date_from: str,
    date_to: str,
) -> list[dict[str, Any]]:
    gift_lower = gift_name.lower()
    sender_lower = sender.lower()
    filtered: list[dict[str, Any]] = []
    for row in rows:
        if source != "all" and row["source"] != source:
            continue
        if gift_lower and gift_lower not in row["gift_name"].lower():
            continue
        if sender_lower and sender_lower not in _sender_search_text(row):
            continue
        row_date = row["date"] or row["event_time"][:10]
        if date_from and row_date < date_from:
            continue
        if date_to and row_date > date_to:
            continue
        filtered.append(row)
    return filtered


def _sort_rows(rows: list[dict[str, Any]], sort: str) -> list[dict[str, Any]]:
    if sort == "score_desc":
        return sorted(rows, key=lambda row: (-row["total_score"], row["event_time"], row["id"]))
    return sorted(rows, key=lambda row: (row["event_time"], row["id"]), reverse=True)


def _summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    room_rows = [row for row in rows if row["source"] == "room"]
    live_rows = [row for row in rows if row["source"] == "live"]
    return {
        "total_records": len(rows),
        "room_records": len(room_rows),
        "live_records": len(live_rows),
        "total_count": sum(row["gift_count"] for row in rows),
        "room_count": sum(row["gift_count"] for row in room_rows),
        "live_count": sum(row["gift_count"] for row in live_rows),
        "total_score": _sum_score(rows),
        "room_score": _sum_score(room_rows),
        "live_score": _sum_score(live_rows),
        "unique_senders": len({_sender_key(row) for row in rows}),
        "gift_kinds": len({_gift_key(row) for row in rows}),
        "active_days": len({row["date"] for row in rows if row["date"]}),
        "live_sessions": len({row["live_id"] for row in live_rows if row["live_id"]}),
        "first_event_time": min((row["event_time"] for row in rows if row["event_time"]), default=""),
        "latest_event_time": max((row["event_time"] for row in rows if row["event_time"]), default=""),
    }


def _gift_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(_gift_key(row), []).append(row)

    output: list[dict[str, Any]] = []
    for (gift_id, gift_name), group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        unit_values = sorted({row["unit_score"] for row in group if row["unit_score"] > 0})
        output.append({
            "gift_id": gift_id,
            "gift_name": gift_name,
            "unit_score": unit_values[0] if len(unit_values) == 1 else None,
            "unit_score_values": unit_values,
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "senders": len({_sender_key(row) for row in group}),
            "gift_icon_url": next((row["gift_icon_url"] for row in group if row["gift_icon_url"]), ""),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: (-float(row["total_score"]), -int(row["total_count"]), str(row["gift_name"])))
    return output


def _sender_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(_sender_key(row), []).append(row)

    output: list[dict[str, Any]] = []
    for sender_group_key, group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        ids = _sender_ids(group)
        names = _sender_names(group)
        output.append({
            "sender_key": sender_group_key,
            "sender_identifier": ids[0] if ids else (names[0] if names else ""),
            "sender_name": _sender_display_name(group, ids),
            "sender_names": names,
            "sender_ids": ids,
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(
        key=lambda row: (
            -float(row["total_score"]),
            -int(row["total_count"]),
            str(row["sender_name"]),
            str(row["sender_identifier"]),
        )
    )
    return output


def _daily_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(row["date"], []).append(row)

    output: list[dict[str, Any]] = []
    for date, group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        output.append({
            "date": date,
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "senders": len({_sender_key(row) for row in group}),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "live_sessions": len({row["live_id"] for row in live_rows if row["live_id"]}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: str(row["date"]), reverse=True)
    return output


def _live_sessions(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        if row["live_id"]:
            groups.setdefault(row["live_id"], []).append(row)

    output: list[dict[str, Any]] = []
    for live_id, group in groups.items():
        first = group[0]
        output.append({
            "live_id": live_id,
            "live_bj_time": first["live_bj_time"],
            "live_title": first["live_title"],
            "date": first["date"],
            "total_score": _sum_score(group),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "senders": len({_sender_key(row) for row in group}),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: str(row["live_bj_time"]), reverse=True)
    return output


def _normalise_distribution(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    return [item for item in items if isinstance(item, dict)]


EXPORT_COLUMNS: tuple[tuple[str, str], ...] = (
    ("source_label", "来源"),
    ("event_time", "送礼时间"),
    ("date", "日期"),
    ("sender_name", "送礼用户"),
    ("sender_id", "送礼用户ID"),
    ("sender_id_match_status", "用户ID匹配状态"),
    ("receiver_name", "收礼成员"),
    ("gift_id", "礼物ID"),
    ("gift_name", "礼物"),
    ("gift_count", "数量"),
    ("unit_score", "单个分值"),
    ("total_score", "总分值"),
    ("score_source", "分值来源"),
    ("fulfillment_label", "回复/业务状态"),
    ("fulfillment_detail", "回复/业务详情"),
    ("fulfillment_time", "回复/业务时间"),
    ("room_reply_count", "房间回复数"),
    ("room_first_reply_time", "房间首条回复时间"),
    ("room_first_reply_content", "房间首条回复内容"),
    ("business_status", "直播业务状态"),
    ("business_type", "直播业务类型"),
    ("business_content", "直播业务内容"),
    ("business_offset", "业务弹幕偏移"),
    ("business_review_status", "业务核实状态"),
    ("business_reviewed_at", "业务核实时间"),
    ("business_evidence", "业务证据"),
    ("business_analysis_reasoning", "业务分析说明"),
    ("live_title", "直播标题"),
    ("live_bj_time", "直播时间"),
    ("live_id", "直播ID"),
    ("danmu_offset", "礼物弹幕偏移"),
    ("danmu_line_number", "礼物弹幕行号"),
    ("message_id", "房间消息ID"),
    ("server_id", "房间服务端ID"),
    ("raw_content", "原始内容"),
    ("id", "记录ID"),
)


def _build_score_gifts_xlsx(rows: list[dict[str, Any]], generated_at: str) -> bytes:
    workbook_files = {
        "[Content_Types].xml": _xlsx_content_types(),
        "_rels/.rels": _xlsx_root_rels(),
        "xl/workbook.xml": _xlsx_workbook(),
        "xl/_rels/workbook.xml.rels": _xlsx_workbook_rels(),
        "xl/styles.xml": _xlsx_styles(),
        "xl/worksheets/sheet1.xml": _xlsx_sheet(rows, generated_at),
        "docProps/core.xml": _xlsx_core_props(),
        "docProps/app.xml": _xlsx_app_props(),
    }
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        for name, content in workbook_files.items():
            archive.writestr(name, content.encode("utf-8"))
    return output.getvalue()


def _xlsx_sheet(rows: list[dict[str, Any]], generated_at: str) -> str:
    all_rows: list[list[Any]] = [
        ["计分礼物明细导出"],
        ["数据生成时间", generated_at],
        ["导出时间", _bj_now()],
        [],
        [label for _, label in EXPORT_COLUMNS],
    ]
    for row in rows:
        all_rows.append([_export_cell_value(row, key) for key, _ in EXPORT_COLUMNS])

    xml_rows = []
    for row_index, values in enumerate(all_rows, start=1):
        cells = []
        for col_index, value in enumerate(values, start=1):
            style = 2 if row_index <= 3 else (1 if row_index == 5 else 0)
            cells.append(_xlsx_cell(row_index, col_index, value, style))
        xml_rows.append(f'<row r="{row_index}">{"".join(cells)}</row>')

    last_row = max(1, len(all_rows))
    last_col = _xlsx_col_name(len(EXPORT_COLUMNS))
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        f'<dimension ref="A1:{last_col}{last_row}"/>'
        '<sheetViews><sheetView workbookViewId="0"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/>'
        '<selection pane="bottomLeft"/></sheetView></sheetViews>'
        '<sheetFormatPr defaultRowHeight="16"/>'
        f'<cols>{_xlsx_columns()}</cols>'
        f'<sheetData>{"".join(xml_rows)}</sheetData>'
        f'<autoFilter ref="A5:{last_col}5"/>'
        '<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>'
        '</worksheet>'
    )


def _export_cell_value(row: dict[str, Any], key: str) -> Any:
    if key == "source_label":
        return row.get("source_label") or _source_text(row.get("source"))
    if key == "business_status":
        status_value = row.get("business_status")
        if status_value == "redeemed":
            return "已兑换业务"
        if status_value == "unredeemed":
            return "未兑换业务"
        if status_value == "uncertain":
            return "待人工核实"
        return status_value
    if key == "business_review_status":
        review = row.get("business_review_status")
        if review == "verified":
            return "已核实"
        if review == "pending_review":
            return "待核实"
        if review == "pending_analysis":
            return "待分析"
        return review
    return row.get(key)


def _source_text(value: Any) -> str:
    if value == "live":
        return "直播"
    if value == "room":
        return "房间"
    return _clean_text(value)


def _xlsx_cell(row_index: int, col_index: int, value: Any, style: int) -> str:
    ref = f"{_xlsx_col_name(col_index)}{row_index}"
    style_attr = f' s="{style}"' if style else ""
    if value is None:
        value = ""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f'<c r="{ref}"{style_attr}><v>{value}</v></c>'
    text = escape(_clean_text(value))
    return f'<c r="{ref}" t="inlineStr"{style_attr}><is><t>{text}</t></is></c>'


def _xlsx_col_name(index: int) -> str:
    name = ""
    while index:
        index, remainder = divmod(index - 1, 26)
        name = chr(65 + remainder) + name
    return name


def _xlsx_columns() -> str:
    widths = [
        10, 20, 12, 18, 16, 16, 14, 14, 16, 9, 11, 11,
        24, 16, 30, 20, 12, 20, 34, 16, 16, 34, 16, 14,
        20, 34, 38, 26, 20, 20, 16, 14, 22, 18, 34, 34,
    ]
    return "".join(
        f'<col min="{index}" max="{index}" width="{width}" customWidth="1"/>'
        for index, width in enumerate(widths, start=1)
    )


def _xlsx_content_types() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
        '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>'
        '<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'
        '</Types>'
    )


def _xlsx_root_rels() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>'
        '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>'
        '</Relationships>'
    )


def _xlsx_workbook() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="计分礼物明细" sheetId="1" r:id="rId1"/></sheets>'
        '</workbook>'
    )


def _xlsx_workbook_rels() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
        '</Relationships>'
    )


def _xlsx_styles() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        '<fonts count="3"><font><sz val="11"/><name val="Calibri"/></font>'
        '<font><b/><sz val="11"/><name val="Calibri"/></font>'
        '<font><b/><sz val="14"/><name val="Calibri"/></font></fonts>'
        '<fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>'
        '<fill><patternFill patternType="solid"><fgColor rgb="FFE8EEF6"/><bgColor indexed="64"/></patternFill></fill></fills>'
        '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
        '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
        '<cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
        '<xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/>'
        '<xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs>'
        '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>'
        '</styleSheet>'
    )


def _xlsx_core_props() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/" '
        'xmlns:dcterms="http://purl.org/dc/terms/" '
        'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        '<dc:title>计分礼物明细导出</dc:title>'
        '<dc:creator>snh48_web</dc:creator>'
        f'<dcterms:created xsi:type="dcterms:W3CDTF">{timestamp}</dcterms:created>'
        f'<dcterms:modified xsi:type="dcterms:W3CDTF">{timestamp}</dcterms:modified>'
        '</cp:coreProperties>'
    )


def _xlsx_app_props() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" '
        'xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
        '<Application>snh48_web</Application>'
        '</Properties>'
    )


def _bj_now() -> str:
    return datetime.now(BJ_TZ).strftime("%Y-%m-%d %H:%M:%S")


def _load_business_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"version": 1, "updated_at": "", "records": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="业务核实状态读取失败") from exc
    if not isinstance(data, dict):
        return {"version": 1, "updated_at": "", "records": {}}
    if not isinstance(data.get("records"), dict):
        data["records"] = {}
    return data


def _record_from_item(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "item_id": item["id"],
        "input_signature": _live_business_item_signature(item),
        "business_type": _clean_text(item.get("business_type")),
        "business_content": _clean_text(item.get("business_content")),
        "business_offset": _clean_text(item.get("business_offset")),
        "business_line_number": _clean_text(item.get("business_line_number")),
        "evidence": _clean_text(item.get("business_evidence")),
        "reasoning": _clean_text(item.get("business_analysis_reasoning")),
        "confidence": _clean_text(item.get("business_analysis_confidence")),
        "analysis_source": _clean_text(item.get("business_analysis_source")) or "codex",
        "analysis_model": _clean_text(item.get("business_analysis_model")),
        "analysis_prompt_version": _to_int(item.get("business_analysis_prompt_version"), 1),
        "analyzed_at": _clean_text(item.get("business_analysis_at")),
        "business_window_seconds": _to_int(item.get("business_window_seconds"), 0),
    }


def _business_fields_from_record(record: dict[str, Any]) -> dict[str, Any]:
    status_value = _normalise_business_status(record.get("status") or record.get("business_status"))
    review_status = _normalise_review_status(record.get("review_status") or record.get("business_review_status"))
    if status_value in BUSINESS_STATUSES and review_status == "pending_analysis":
        review_status = "pending_review"
    business_type = _clean_text(record.get("business_type"))
    business_content = _clean_text(record.get("business_content"))
    evidence = _clean_text(record.get("evidence") or record.get("business_evidence"))
    reasoning = _clean_text(record.get("reasoning") or record.get("business_analysis_reasoning"))
    return {
        "fulfillment_status": status_value,
        "fulfillment_label": _business_label(status_value),
        "fulfillment_detail": _business_detail(status_value, business_type, business_content, evidence, reasoning),
        "fulfillment_time": "",
        "fulfillment_source": _clean_text(record.get("analysis_source")) or "codex_live_business_analysis",
        "business_status": status_value,
        "business_type": business_type,
        "business_content": business_content,
        "business_offset": _clean_text(record.get("business_offset")),
        "business_line_number": _clean_text(record.get("business_line_number")),
        "business_window_seconds": _to_int(record.get("business_window_seconds"), 0),
        "business_review_status": review_status,
        "business_reviewed_at": _clean_text(record.get("reviewed_at")),
        "business_reviewed_by": _clean_text(record.get("reviewed_by")),
        "business_analysis_source": _clean_text(record.get("analysis_source")),
        "business_analysis_model": _clean_text(record.get("analysis_model")),
        "business_analysis_prompt_version": _to_int(record.get("analysis_prompt_version"), 1),
        "business_analysis_at": _clean_text(record.get("analyzed_at")),
        "business_analysis_confidence": _clean_text(record.get("confidence")),
        "business_analysis_reasoning": reasoning,
        "business_evidence": evidence,
    }


def _apply_business_state_overrides(rows: list[dict[str, Any]]) -> None:
    state = _load_business_state(_business_state_path())
    records = state.get("records") if isinstance(state, dict) else {}
    if not isinstance(records, dict):
        return
    for row in rows:
        if row.get("source") != "live":
            continue
        record = records.get(row.get("id"))
        if not isinstance(record, dict):
            continue
        signature = _live_business_item_signature(row)
        if _clean_text(record.get("input_signature")) != signature:
            continue
        row.update(_business_fields_from_record(record))


def _normalise_business_status(value: Any) -> str:
    value = _clean_text(value).lower()
    return value if value in BUSINESS_STATUSES else "pending_analysis"


def _normalise_review_status(value: Any) -> str:
    value = _clean_text(value).lower()
    return value if value in {"pending_analysis", "pending_review", "verified"} else "pending_analysis"


def _business_label(status_value: str) -> str:
    if status_value == "redeemed":
        return "已兑换业务"
    if status_value == "unredeemed":
        return "未兑换业务"
    if status_value == "uncertain":
        return "待人工核实"
    return "待分析"


def _business_detail(status_value: str, business_type: str, business_content: str, evidence: str, reasoning: str) -> str:
    if status_value == "redeemed":
        parts = [part for part in (business_type, business_content) if part]
        return "：".join(parts) if parts else "已兑换业务"
    if status_value == "unredeemed":
        return business_content if business_content and business_content != "未兑换业务" else "未找到明确业务兑换"
    if status_value == "uncertain":
        return business_content or evidence or reasoning or "无法高置信度判断"
    return "等待分析"


def _live_business_item_signature(item: dict[str, Any]) -> str:
    payload = {field: _signature_value(item.get(field)) for field in SIGNATURE_FIELDS}
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _signature_value(value: Any) -> Any:
    return _clean_text(value)


def _clean_text(value: Any) -> str:
    return str(value or "").strip()


def _valid_sender_name(value: Any) -> bool:
    return _clean_text(value) not in UNKNOWN_SENDER_VALUES


def _valid_sender_id(value: Any) -> bool:
    return _clean_text(value) not in UNKNOWN_SENDER_VALUES


def _sender_key(row: dict[str, Any]) -> str:
    sender_id = _clean_text(row.get("sender_id"))
    if _valid_sender_id(sender_id):
        return f"id:{sender_id}"
    sender_name = _clean_text(row.get("sender_name"))
    if _valid_sender_name(sender_name):
        return f"name:{sender_name}"
    return "unknown:未知用户"


def _sender_search_text(row: dict[str, Any]) -> str:
    return " ".join((
        _clean_text(row.get("sender_name")),
        _clean_text(row.get("sender_id")),
        _sender_key(row),
    )).lower()


def _sender_names(rows: list[dict[str, Any]]) -> list[str]:
    return sorted({_clean_text(row.get("sender_name")) for row in rows if _valid_sender_name(row.get("sender_name"))})


def _sender_ids(rows: list[dict[str, Any]]) -> list[str]:
    return sorted({_clean_text(row.get("sender_id")) for row in rows if _valid_sender_id(row.get("sender_id"))})


def _sender_display_name(rows: list[dict[str, Any]], ids: list[str]) -> str:
    for row in rows:
        name = _clean_text(row.get("sender_name"))
        if _valid_sender_name(name):
            return name
    return f"ID {ids[0]}" if ids else "未知用户"


def _gift_key(row: dict[str, Any]) -> tuple[str, str]:
    return str(row.get("gift_id", "")), str(row.get("gift_name", ""))


def _sum_score(rows: list[dict[str, Any]]) -> float:
    return round(sum(float(row.get("total_score") or 0) for row in rows), 6)


def _validate_date(label: str, value: str) -> None:
    if value and not DATE_RE.match(value.strip()):
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=f"{label} 日期格式应为 YYYY-MM-DD")


def _to_int(value: Any, default: int) -> int:
    if value in (None, ""):
        return default
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


def _to_float(value: Any, default: float) -> float:
    if value in (None, ""):
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default
