"""
Score gifts API router.

Reads the small derived scoring gift dataset generated by snh48-fan-hub and
exposes password-protected statistics and detail rows for the admin dashboard.
"""
from __future__ import annotations

import hmac
import json
import re
import threading
from math import ceil
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request, Response, status

from website import config as cfg
from website.rate_limiter import check_admin_login_limit, get_client_ip

router = APIRouter(prefix="/api/score-gifts", tags=["计分礼物页"])

VALID_SOURCES = {"all", "room", "live"}
VALID_SORTS = {"time_desc", "score_desc"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

_cache_lock = threading.Lock()
_cache_mtime_ns = -1
_cache_doc: dict[str, Any] = {}


async def verify_score_gifts_password(
    request: Request,
    x_score_gifts_password: str = Header(None, alias="X-Score-Gifts-Password"),
):
    """Verify the score gifts page password."""
    expected = cfg.SCORE_GIFTS_PASSWORD
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="计分礼物页未启用",
        )
    if not x_score_gifts_password:
        check_score_gifts_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="需要密码",
        )
    if not hmac.compare_digest(expected, x_score_gifts_password):
        check_score_gifts_login_limit(request)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="密码错误",
        )
    return True


def check_score_gifts_login_limit(request: Request) -> None:
    check_admin_login_limit(get_client_ip(request), "计分礼物页密码尝试过于频繁，请稍后再试")


@router.get("/data")
def get_score_gifts_data(
    response: Response,
    page: int = Query(1, ge=1),
    page_size: int = Query(100, ge=1, le=500),
    source: str = Query("all"),
    gift_name: str = Query(""),
    sender: str = Query(""),
    date_from: str = Query(""),
    date_to: str = Query(""),
    sort: str = Query("time_desc"),
    _=Depends(verify_score_gifts_password),
):
    """Return filtered score gift statistics and paginated detail rows."""
    response.headers["Cache-Control"] = "no-store"

    source = source.strip().lower()
    sort = sort.strip().lower()
    if source not in VALID_SOURCES:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的数据来源")
    if sort not in VALID_SORTS:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="无效的排序方式")
    _validate_date("date_from", date_from)
    _validate_date("date_to", date_to)
    if date_from and date_to and date_from > date_to:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="日期范围无效")

    doc = _load_dataset()
    rows = _filter_rows(
        _normalise_items(doc.get("items", [])),
        source=source,
        gift_name=gift_name.strip(),
        sender=sender.strip(),
        date_from=date_from.strip(),
        date_to=date_to.strip(),
    )
    rows = _sort_rows(rows, sort)

    total = len(rows)
    total_pages = max(1, ceil(total / page_size))
    start = (page - 1) * page_size
    end = start + page_size

    return {
        "generated_at": str(doc.get("generated_at", "")),
        "timezone": str(doc.get("timezone", "Asia/Shanghai")),
        "refresh_interval_seconds": _to_int(doc.get("refresh_interval_seconds"), 30),
        "default_page_size": _to_int(doc.get("default_page_size"), 100),
        "summary": doc.get("summary", {}),
        "filtered_summary": _summary(rows),
        "gift_catalog": _normalise_distribution(doc.get("gift_catalog") or doc.get("gift_distribution") or []),
        "gift_distribution": _gift_distribution(rows),
        "sender_distribution": _sender_distribution(rows),
        "daily_distribution": _daily_distribution(rows),
        "live_sessions": _live_sessions(rows),
        "items": rows[start:end],
        "page": page,
        "page_size": page_size,
        "total": total,
        "total_pages": total_pages,
    }


@router.get("/summary")
def get_score_gifts_summary(
    response: Response,
    _=Depends(verify_score_gifts_password),
):
    """Return score gift summary metadata without detail rows."""
    response.headers["Cache-Control"] = "no-store"
    doc = _load_dataset()
    return {
        "generated_at": str(doc.get("generated_at", "")),
        "timezone": str(doc.get("timezone", "Asia/Shanghai")),
        "refresh_interval_seconds": _to_int(doc.get("refresh_interval_seconds"), 30),
        "default_page_size": _to_int(doc.get("default_page_size"), 100),
        "summary": doc.get("summary", {}),
        "gift_distribution": _normalise_distribution(doc.get("gift_distribution", [])),
        "sender_distribution": _normalise_distribution(doc.get("sender_distribution", [])),
        "daily_distribution": _normalise_distribution(doc.get("daily_distribution", [])),
        "live_sessions": _normalise_distribution(doc.get("live_sessions", [])),
    }


def _data_path() -> Path:
    return Path(cfg.SCORE_GIFTS_DATA_PATH)


def _load_dataset() -> dict[str, Any]:
    global _cache_mtime_ns, _cache_doc

    path = _data_path()
    if not path.exists():
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据未生成")

    stat = path.stat()
    if _cache_mtime_ns == stat.st_mtime_ns:
        return _cache_doc

    with _cache_lock:
        stat = path.stat()
        if _cache_mtime_ns == stat.st_mtime_ns:
            return _cache_doc
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据读取失败") from exc
        if not isinstance(doc, dict):
            raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="计分礼物数据格式无效")
        _cache_mtime_ns = stat.st_mtime_ns
        _cache_doc = doc
        return _cache_doc


def _normalise_items(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    rows: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        rows.append({
            "id": str(item.get("id", "")),
            "source": str(item.get("source", "")),
            "source_label": str(item.get("source_label", "")),
            "event_time": str(item.get("event_time", "")),
            "date": str(item.get("date", "")),
            "sender_name": str(item.get("sender_name", "")),
            "sender_id": str(item.get("sender_id", "")),
            "receiver_name": str(item.get("receiver_name", "")),
            "gift_id": str(item.get("gift_id", "")),
            "gift_name": str(item.get("gift_name", "")),
            "gift_count": _to_int(item.get("gift_count"), 0),
            "unit_score": _to_float(item.get("unit_score"), 0.0),
            "total_score": _to_float(item.get("total_score"), 0.0),
            "score_source": str(item.get("score_source", "")),
            "gift_icon_url": str(item.get("gift_icon_url", "")),
            "gift_media_path": str(item.get("gift_media_path", "")),
            "message_id": str(item.get("message_id", "")),
            "server_id": str(item.get("server_id", "")),
            "source_jsonl_lineno": str(item.get("source_jsonl_lineno", "")),
            "live_id": str(item.get("live_id", "")),
            "live_title": str(item.get("live_title", "")),
            "live_bj_time": str(item.get("live_bj_time", "")),
            "danmu_offset": str(item.get("danmu_offset", "")),
            "danmu_file": str(item.get("danmu_file", "")),
            "danmu_line_number": str(item.get("danmu_line_number", "")),
            "raw_content": str(item.get("raw_content", "")),
        })
    return rows


def _filter_rows(
    rows: list[dict[str, Any]],
    *,
    source: str,
    gift_name: str,
    sender: str,
    date_from: str,
    date_to: str,
) -> list[dict[str, Any]]:
    gift_lower = gift_name.lower()
    sender_lower = sender.lower()
    filtered: list[dict[str, Any]] = []
    for row in rows:
        if source != "all" and row["source"] != source:
            continue
        if gift_lower and gift_lower not in row["gift_name"].lower():
            continue
        if sender_lower and sender_lower not in row["sender_name"].lower():
            continue
        row_date = row["date"] or row["event_time"][:10]
        if date_from and row_date < date_from:
            continue
        if date_to and row_date > date_to:
            continue
        filtered.append(row)
    return filtered


def _sort_rows(rows: list[dict[str, Any]], sort: str) -> list[dict[str, Any]]:
    if sort == "score_desc":
        return sorted(rows, key=lambda row: (-row["total_score"], row["event_time"], row["id"]))
    return sorted(rows, key=lambda row: (row["event_time"], row["id"]), reverse=True)


def _summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    room_rows = [row for row in rows if row["source"] == "room"]
    live_rows = [row for row in rows if row["source"] == "live"]
    return {
        "total_records": len(rows),
        "room_records": len(room_rows),
        "live_records": len(live_rows),
        "total_count": sum(row["gift_count"] for row in rows),
        "room_count": sum(row["gift_count"] for row in room_rows),
        "live_count": sum(row["gift_count"] for row in live_rows),
        "total_score": _sum_score(rows),
        "room_score": _sum_score(room_rows),
        "live_score": _sum_score(live_rows),
        "unique_senders": len({_sender_key(row) for row in rows}),
        "gift_kinds": len({_gift_key(row) for row in rows}),
        "active_days": len({row["date"] for row in rows if row["date"]}),
        "live_sessions": len({row["live_id"] for row in live_rows if row["live_id"]}),
        "first_event_time": min((row["event_time"] for row in rows if row["event_time"]), default=""),
        "latest_event_time": max((row["event_time"] for row in rows if row["event_time"]), default=""),
    }


def _gift_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(_gift_key(row), []).append(row)

    output: list[dict[str, Any]] = []
    for (gift_id, gift_name), group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        unit_values = sorted({row["unit_score"] for row in group if row["unit_score"] > 0})
        output.append({
            "gift_id": gift_id,
            "gift_name": gift_name,
            "unit_score": unit_values[0] if len(unit_values) == 1 else None,
            "unit_score_values": unit_values,
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "senders": len({_sender_key(row) for row in group}),
            "gift_icon_url": next((row["gift_icon_url"] for row in group if row["gift_icon_url"]), ""),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: (-float(row["total_score"]), -int(row["total_count"]), str(row["gift_name"])))
    return output


def _sender_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(_sender_key(row), []).append(row)

    output: list[dict[str, Any]] = []
    for sender_name, group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        output.append({
            "sender_name": sender_name,
            "sender_ids": sorted({row["sender_id"] for row in group if row["sender_id"]}),
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: (-float(row["total_score"]), -int(row["total_count"]), str(row["sender_name"])))
    return output


def _daily_distribution(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(row["date"], []).append(row)

    output: list[dict[str, Any]] = []
    for date, group in groups.items():
        room_rows = [row for row in group if row["source"] == "room"]
        live_rows = [row for row in group if row["source"] == "live"]
        output.append({
            "date": date,
            "total_score": _sum_score(group),
            "room_score": _sum_score(room_rows),
            "live_score": _sum_score(live_rows),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "room_records": len(room_rows),
            "live_records": len(live_rows),
            "senders": len({_sender_key(row) for row in group}),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "live_sessions": len({row["live_id"] for row in live_rows if row["live_id"]}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: str(row["date"]), reverse=True)
    return output


def _live_sessions(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        if row["live_id"]:
            groups.setdefault(row["live_id"], []).append(row)

    output: list[dict[str, Any]] = []
    for live_id, group in groups.items():
        first = group[0]
        output.append({
            "live_id": live_id,
            "live_bj_time": first["live_bj_time"],
            "live_title": first["live_title"],
            "date": first["date"],
            "total_score": _sum_score(group),
            "total_count": sum(row["gift_count"] for row in group),
            "records": len(group),
            "senders": len({_sender_key(row) for row in group}),
            "gift_kinds": len({_gift_key(row) for row in group}),
            "first_event_time": min((row["event_time"] for row in group if row["event_time"]), default=""),
            "latest_event_time": max((row["event_time"] for row in group if row["event_time"]), default=""),
        })
    output.sort(key=lambda row: str(row["live_bj_time"]), reverse=True)
    return output


def _normalise_distribution(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    return [item for item in items if isinstance(item, dict)]


def _sender_key(row: dict[str, Any]) -> str:
    return str(row.get("sender_name") or row.get("sender_id") or "未知用户")


def _gift_key(row: dict[str, Any]) -> tuple[str, str]:
    return str(row.get("gift_id", "")), str(row.get("gift_name", ""))


def _sum_score(rows: list[dict[str, Any]]) -> float:
    return round(sum(float(row.get("total_score") or 0) for row in rows), 6)


def _validate_date(label: str, value: str) -> None:
    if value and not DATE_RE.match(value.strip()):
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=f"{label} 日期格式应为 YYYY-MM-DD")


def _to_int(value: Any, default: int) -> int:
    if value in (None, ""):
        return default
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


def _to_float(value: Any, default: float) -> float:
    if value in (None, ""):
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default
